import { Col, Row, Container, Tab, Nav } from "react-bootstrap";
import { ProjectCard } from "./ProjectCard";
import colorSharp2 from "../assets/img/color-sharp2.png";
import todo from "../assets/img/todo.png";
import homeautomation from "../assets/img/homeautomation.jpeg";
import justajoke from "../assets/img/justajoke.png";
import weatherapp from "../assets/img/weatherapp.png";
import tictactoe from "../assets/img/tictactoe.png";
import sudokusolver from "../assets/img/sudokusolver.png";
import ecom from "../assets/img/ecom.png";
import dashboard from "../assets/img/dashboard.png";
import qr from "../assets/img/QRimage.png";
import projectsicon from "../assets/img/projectsicon.svg";

export const Projects = () => {
    const Webprojects = [
        {
            title: "Weather App",
            description: <p>Experience the Weather App, provides up-to-date weather forecasts tailored to your location. Stay informed with accurate weather data, including temperature, and humidity chances.</p>,
            imgUrl: weatherapp,
            linkUrl: "https://temperatureinyourscity.netlify.app/",
        },
        {
            title: "To Do website",
            description: <p>It is a basic to-do website that takes the inputs from the user which describe the work they need to do later and saves them until you clear them manually.</p>,
            imgUrl: todo,
            linkUrl: "https://coruscating-cuchufli-a317c0.netlify.app/", 
        },
        {
            title: "Just A Joke",
            description: <p>This is a basic Google extension that generates a random joke when tapped. It uses an API from the browser and fetches a random joke generated by that site.</p>,
            imgUrl: justajoke,
            linkUrl: "https:/github.com/tsrithvik/myextensions.git",
        },
    ];

    const Progprojects = [
        {
            title: "TIC TAC TOE Game",
            description: "Using Java programming language, a two-player game that can run in any Java IDE. This project challenged me to apply my programming skills in Java, including array manipulation, user input handling, and logical decision-making.",
            imgUrl: tictactoe,
            linkUrl: "https://github.com/tsrithvik/tictactoe.git",
        },
        {
            title: "SUDOKU Solver",
            description: "Whether you're a Sudoku pro or just enjoy a good brain teaser, this tool will make solving a breeze. This might help you to compare your results with its actual solution. Used simple algorithms like recursion and backtracking to achieve this, which was written in Java programming language.",
            imgUrl: sudokusolver,
            linkUrl: "https://github.com/tsrithvik/Sudoku-Solver.git",
        },
    ];

    const Coreprojects = [
        {
            title: "Home Automation",
            description: "Designed and developed a centralized control system using ESP32 and wireless communication using WiFi to control the household devices and appliances remotely.",
            imgUrl: homeautomation,
            linkUrl: "",
        },
        {
            title: "Data Analysis using EXCEL",
            description: "Dashboard or a pivot table which was developed using excel data sheet to visualize the usage and development of programming languages over time.",
            imgUrl: dashboard,
            linkUrl: "",
        },
        {
            title: "QR generator",
            description: "Creates a new QR coded image by taking some text input of links and generates a QR image from it. Used APIs from the browser and developed using NODE.JS and EJS.",
            imgUrl: qr,
            linkUrl: "https://github.com/tsrithvik/VS-Code.git",
        },
    ];

    return (
        <section className='project' id='projects'>
            <Container>
                <Row>
                    <Col>
                    <div className="project-bx">
                        <h2 style={{ color: 'white' }}>
                            Projects
                            <div style={{ display: 'flex', justifyContent: 'space-around' }}>
                                <img src={projectsicon} alt="Projects-img" style={{ height: '50px', width: '50px' }} />
                            </div>
                        </h2>
                        <p>This section describes my projects from different fields. These are the projects I've developed as an outcome of my knowledge in different courses. Lots of research and many tutors helped me to develop them. It encompasses a range of technical and soft skills that I have developed through online courses, hands-on projects, and professional experiences.</p>
                        <Tab.Container id="projects-tabs" defaultActiveKey="first">
                            <Nav variant="tabs" className="nav-pills mb-5 justify-content-center align-items-center" id="pills-tab">
                                <Nav.Item>
                                    <Nav.Link eventKey="first">Web Development</Nav.Link>
                                </Nav.Item>
                                <Nav.Item>
                                    <Nav.Link eventKey="second">Programming</Nav.Link>
                                </Nav.Item>
                                <Nav.Item>
                                    <Nav.Link eventKey="third">Core & Other</Nav.Link>
                                </Nav.Item>
                            </Nav>
                            <Tab.Content>
                                <Tab.Pane eventKey="first">
                                    <Row>
                                        {Webprojects.map((project, index) => (
                                            <ProjectCard key={index} {...project} />
                                        ))}
                                    </Row>
                                </Tab.Pane>
                                <Tab.Pane eventKey="second">
                                    <Row>
                                        {Progprojects.map((project, index) => (
                                            <ProjectCard key={index} {...project} />
                                        ))}
                                    </Row>
                                </Tab.Pane>
                                <Tab.Pane eventKey="third">
                                    <Row>
                                        {Coreprojects.map((project, index) => (
                                            <ProjectCard key={index} {...project} />
                                        ))}
                                    </Row>
                                </Tab.Pane>
                            </Tab.Content>
                        </Tab.Container>
                        </div>
                    </Col>
                </Row>
            </Container>
            <img className='bg-img-right' src={colorSharp2} alt="Background" />
        </section>
    )
}
